FROM node:alpine as build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
COPY . ./
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install serve -g
ENTRYPOINT serve -s build -l 80